# This file was generated by GoReleaser. DO NOT EDIT.
cask "claws" do
  version "0.18.101"

  on_macos do
    on_intel do
      sha256 "eccced3323e5db4a6c4b7eb4f39fe56e1b32eed3a166cec47bdfd6adf2732571"
      url "https://github.com/abhijit-s/claws/releases/download/v#{version}/claws-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "e62ee27e6525c2f1944b689f690f6b0e7412ac42078911d8845f64bd4ce4763b"
      url "https://github.com/abhijit-s/claws/releases/download/v#{version}/claws-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58d1b2014e326de75cbb1020f84c454d778058e3cde5884cedd3fbb97b971a45"
      url "https://github.com/abhijit-s/claws/releases/download/v#{version}/claws-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "86ff6c1a6e7918bc084fce629128384650b03e209842fb4d4f0a125460f07205"
      url "https://github.com/abhijit-s/claws/releases/download/v#{version}/claws-linux-arm64.tar.gz"
    end
  end

  name "claws"
  desc "Terminal UI for AWS resource management"
  homepage "https://github.com/clawscli/claws"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claws"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claws"]
    end
  end

  # No zap stanza required

end
